package com.example.hunterqrhunter.page;

import android.graphics.Bitmap;
import android.os.Bundle;
import android.provider.Settings;
import android.util.Log;
import android.widget.Button;
import android.widget.EditText;
import android.widget.GridView;
import android.widget.ImageView;
import android.widget.ListView;

import androidx.annotation.Nullable;
import androidx.appcompat.app.AppCompatActivity;

import com.example.hunterqrhunter.R;
import com.example.hunterqrhunter.model.HashQR;
import com.google.firebase.firestore.CollectionReference;
import com.google.firebase.firestore.DocumentSnapshot;
import com.google.firebase.firestore.FieldPath;
import com.google.firebase.firestore.FirebaseFirestore;

import java.util.ArrayList;
import java.util.concurrent.atomic.AtomicInteger;

public class MyQRScreen extends AppCompatActivity {
    {/**
     [v]MyQRScreen has all the QRs the player acquired
     [v]Number of the Qrs
     [v]Score of the player
     [v]Player can delete the QR if they want to
     */}
    private FirebaseFirestore db;
    @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_my_qr);

        //unique user ID generated by the device
        String userID = Settings.Secure.getString(getContentResolver(), Settings.Secure.ANDROID_ID);

        //Initialize firestore database
        db = FirebaseFirestore.getInstance();

        //get the total score of the user
        AtomicInteger totalScore = new AtomicInteger(0);

        //total number of the QRs
        AtomicInteger totalQRs = new AtomicInteger();

        //get the QR collection
        CollectionReference qrRef = db.collection("QR");

        //arrayList to store the QRs
        ArrayList<Bitmap> qrList = new ArrayList<>();

        //arrayList to store the qid
        ArrayList<String> qidList = new ArrayList<>();

        //Initialize the HashQR class
        HashQR hashQR = new HashQR();

        //button for delete the QR
        Button DeleteButton = findViewById(R.id.QR_delete_button);
        GridView faceList = findViewById(R.id.QRList);
        EditText qrText = findViewById(R.id.NumQR);
        EditText scoreText = findViewById(R.id.UserScore);
        FaceListAdapter adapter = new FaceListAdapter(this, qrList);

        AtomicInteger ItemPostion = new AtomicInteger();

        //when the user click any item in the facelist Listview
        faceList.setOnItemClickListener((parent, view, position, id) -> {
            ItemPostion.set(position);
        });

        //delete the qr from the database that the user clicked from ListView QRList
        DeleteButton.setOnClickListener(v -> {
            //get the qid of the QR that the user clicked
            String qid = qidList.get(ItemPostion.get());
            qidList.remove(ItemPostion.get());
            qrList.remove(ItemPostion.get());
            //update the total number of the QRs
            totalQRs.getAndDecrement();
            //delete the QR from the database
            qrRef.whereEqualTo(FieldPath.of("qid"), qid).get().addOnCompleteListener(task -> {
                if (task.isSuccessful()) {
                    for (DocumentSnapshot document : task.getResult()) {
                        //update the total score from database that the user deleted
                        Object score = document.get("score");

                        //update the total score
                        totalScore.addAndGet(-Integer.parseInt(score.toString()));

                        //delete the QR from the database
                        document.getReference().delete();

                        //update the total score
                        scoreText.setText(totalScore.toString());

                        //update the total number of the QRs
                        qrText.setText(totalQRs.toString());

                        //update the ListView
                        adapter.notifyDataSetChanged();
                    }
                }
            });

        });

        //if userID and qrRef's uid is the same, then get the score of the user
        qrRef.whereEqualTo(FieldPath.of("uid"), userID).get().addOnCompleteListener(task -> {
            if (task.isSuccessful()) {
                ImageView faceImageView = null;
                Bitmap faceBitmap = null;
                Bitmap bitmap = null;
                for (DocumentSnapshot document : task.getResult()) {

                    //get the score of the user and add it to the total score
                    Integer score = Integer.parseInt(document.getData().get("score").toString());

                    //update the total score
                    totalScore.addAndGet(score);

                    //update the total number of the QRs
                    totalQRs.getAndIncrement();

                    //get the qrcode field from the QR document
                    String qrCode = document.getData().get("qrcode").toString();

                    //get the qid field from the QR document
                    String qid = document.getData().get("qid").toString();

                    //add the qid to the qidList
                    qidList.add(qid);

                    //create a face class based on the qrCode
                    byte[] hash = hashQR.hashObject(qrCode);
                    faceBitmap = hashQR.generateImageFromHashcode(hash);
                    bitmap = Bitmap.createBitmap(faceBitmap);
                    qrList.add(bitmap);

                    Log.d("MyQRScreen", document.getId() + " => " + document.getData());
                }

                scoreText.setText(totalScore.toString());

                qrText.setText(totalQRs.toString());


                faceList.setAdapter(adapter);

            } else {
                Log.d("MyQRScreen", "Error getting documents: ", task.getException());
            }
        });


    }
}
